-- SUPERSEDED BY MIGRATION: 20260615_restore_get_user_id_by_phone.sql
-- Do not run this file. The get_user_id_by_phone RPC is now managed correctly
-- in the migrations folder with proper 10-digit normalization logic.
