import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabaseServer";

export async function GET(req, { params }) {
  const { id } = await params;
  if (!id || typeof id !== "string") {
    return NextResponse.json({ error: "Invalid sponsorship id" }, { status: 400 });
  }

  const supabase = createAdminClient();
  const { data: booking, error: bErr } = await supabase
    .from("daily_challenge_sponsorships")
    .select(
      "id, sponsor_date, merchant_id, fee_paise, status, merchant:merchants(business_name)"
    )
    .eq("id", id)
    .single();

  if (bErr || !booking) {
    return NextResponse.json({ error: "Sponsorship not found" }, { status: 404 });
  }

  const merchantName = booking.merchant?.business_name || "Merchant";
  const invoiceNumber = `INV-SPON-${booking.id.slice(0, 8).toUpperCase()}`;
  const dateStr = booking.sponsor_date
    ? new Date(booking.sponsor_date).toLocaleDateString("en-IN", {
        weekday: "long",
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : "N/A";
  const amountStr = booking.fee_paise ? `₹${(booking.fee_paise / 100).toFixed(2)}` : "₹0.00";

  const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>${invoiceNumber} - GST Invoice</title>
<style>
  body { font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; padding: 32px; color: #1f2937; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .meta { color: #4b5563; font-size: 14px; margin-bottom: 18px; }
  .line { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e5e7eb; }
  .line:last-child { border-bottom: none; }
  .label { color: #6b7280; }
  .val { font-weight: 600; }
  .note { margin-top: 18px; color: #6b7280; font-size: 12px; }
</style>
</head>
<body>
  <h1>${invoiceNumber}</h1>
  <div class="meta">GST Invoice — Daily Challenge Sponsorship</div>
  <div class="line"><span class="label">Bill To</span><span class="val">${merchantName}</span></div>
  <div class="line"><span class="label">Sponsor Date</span><span class="val">${dateStr}</span></div>
  <div class="line"><span class="label">Amount Paid</span><span class="val">${amountStr}</span></div>
  <div class="line"><span class="label">Sponsorship ID</span><span class="val">${booking.id}</span></div>
  <div class="line"><span class="label">Status</span><span class="val">${booking.status}</span></div>
  <div class="note">Generated by Intrust India Marketing Panel.</div>
</body>
</html>
`.trim();

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `inline; filename="${invoiceNumber}.html"`,
    },
  });
}
