/**
 * Converts a string to a URL-safe slug.
 * Note: the canonical slug always comes from the DB (generated by the trigger).
 * This utility is useful for client-side display/link generation from object data.
 *
 * @param {string} text - The input string to slugify.
 * @returns {string} - The slugified string.
 */
export function slugify(text) {
    if (!text) return '';
    return text
        .toString()
        .toLowerCase()
        .trim()
        .replace(/[^a-z0-9]+/g, '-')   // Replace non-alphanumeric sequences with hyphens
        .replace(/^-+|-+$/g, '')         // Trim leading/trailing hyphens
        .replace(/-{2,}/g, '-');         // Collapse multiple consecutive hyphens
}
