-- ============================================================
-- INTRUST INDIA — P8: Storage RLS Lockdown
-- Migration: 20260812_p8_storage_rls_lockdown.sql
--
-- Addresses FINDING-A16: Open INSERT policies on multiple storage buckets.
-- Many buckets had empty (unrestricted) INSERT policies allowing any
-- authenticated user to upload arbitrary files to any path, bypassing quota
-- and ownership controls.
--
-- Date: 2026-08-12
-- ============================================================

BEGIN;

-- 1. Avatars
DROP POLICY IF EXISTS "Users can upload their own avatar" ON storage.objects;
CREATE POLICY "Users can upload their own avatar"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'avatars' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- 2. Attendance Selfies
DROP POLICY IF EXISTS "Authenticated users can upload selfies" ON storage.objects;
CREATE POLICY "Authenticated users can upload selfies"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'attendance-selfies' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- 3. Resumes
DROP POLICY IF EXISTS "Applicants can upload resumes" ON storage.objects;
CREATE POLICY "Applicants can upload resumes"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'resumes' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- 4. Payslips
DROP POLICY IF EXISTS "Payslips can be uploaded by HR" ON storage.objects;
CREATE POLICY "Payslips can be uploaded by HR"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'payslips' AND
  EXISTS (
    SELECT 1 FROM public.user_profiles
    WHERE id = auth.uid() AND role IN ('hr_manager', 'admin', 'super_admin')
  )
);

-- 5. Merchant Banners
DROP POLICY IF EXISTS "Allow authenticated uploads merchant_banners" ON storage.objects;
CREATE POLICY "Allow authenticated uploads merchant_banners"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'merchant_banners' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- 6. Product Images (Admin and Merchant)
DROP POLICY IF EXISTS "Admin can upload product images" ON storage.objects;
CREATE POLICY "Admin can upload product images"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'product-images' AND
  EXISTS (
    SELECT 1 FROM public.user_profiles
    WHERE id = auth.uid() AND role IN ('admin', 'super_admin')
  )
);

DROP POLICY IF EXISTS "Merchant can upload own product images" ON storage.objects;
CREATE POLICY "Merchant can upload own product images"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'product-images' AND
  (storage.foldername(name))[1] = 'merchant' AND
  (storage.foldername(name))[2] = auth.uid()::text
);

-- 7. Banners
DROP POLICY IF EXISTS "Admin Uploads for Banners" ON storage.objects;
CREATE POLICY "Admin Uploads for Banners"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'banners' AND
  EXISTS (
    SELECT 1 FROM public.user_profiles
    WHERE id = auth.uid() AND role IN ('admin', 'super_admin')
  )
);

-- 8. Gift Cards (Extremely permissive default policies generated by UI)
DROP POLICY IF EXISTS "Allow all operations 1jiijd2_0" ON storage.objects;
DROP POLICY IF EXISTS "Allow all operations 1jiijd2_1" ON storage.objects;
DROP POLICY IF EXISTS "Allow all operations 1jiijd2_2" ON storage.objects;
DROP POLICY IF EXISTS "Allow all operations 1jiijd2_3" ON storage.objects;

-- Only admins should manage gift card graphics
CREATE POLICY "Admins can manage gift cards"
ON storage.objects FOR ALL
USING (
  bucket_id = 'gift-cards' AND
  EXISTS (
    SELECT 1 FROM public.user_profiles
    WHERE id = auth.uid() AND role IN ('admin', 'super_admin')
  )
)
WITH CHECK (
  bucket_id = 'gift-cards' AND
  EXISTS (
    SELECT 1 FROM public.user_profiles
    WHERE id = auth.uid() AND role IN ('admin', 'super_admin')
  )
);

CREATE POLICY "Public can view gift cards"
ON storage.objects FOR SELECT
USING (bucket_id = 'gift-cards');

COMMIT;
